<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>WeatherLink_Live_Library</RootNamespace>
	 <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
	  <!-- brings in System.Net.Http -->
	  <LangVersion>latest</LangVersion>
	  <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="IsExternalInit" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="log4net" Version="3.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	 <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>
</Project>